### ISSUE TITLE
語録にMINSUKE SUMEPOKO(以下略)やPANPOKO SUNPEがない

### ISSUE THREAD

**Issue by hidekitux** [snct-ukai/zaki_saying#1]
![image](https://user-images.githubusercontent.com/59034394/166096506-0341025e-fa28-4279-9593-6bafe72c1b6d.png)

**Comment by ukaaaai** [comment]
その文字に対応させるのめんどくさいのでそういう仕様にしますあとdiscordから収集もめんどくさいのでこれも仕様に...

**Comment by hidekitux** [comment]
_**OOPS**_
